name: Deploy doxygen to Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@edge
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: "./Docs"

      - name: Add .nojekyll
        run: sudo touch ./Docs/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./Docs/html

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
